name: proxy_setting_platform_interface
description: Flutter plugin for detect proxy setting
repository: https://github.com/ueki-tomohiro/proxy_setting/tree/main/packages/proxy_setting_platform_interface
version: 0.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
